# Generated by Django 3.1.2 on 2020-10-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
